[package]
name = "crabfit_backend"
version = "1.1.0"
edition = "2021"

[workspace]
members = ["data", "adaptors/*"]

[dependencies]
axum = "0.6.18"
serde = { version = "1.0.162", features = ["derive"] }
tokio = { version = "1.28.0", features = ["macros", "rt-multi-thread"] }
data = { path = "data" }
sql-adaptor = { path = "adaptors/sql" }
dotenv = "0.15.0"
