name: API Checks

on:
  pull_request:
    paths:
      - api/**
      - .github/workflows/check_api.yml
  push:
    branches:
      - main
    paths:
      - api/**
      - .github/workflows/check_api.yml

# Fail on warnings
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: api

    steps:
      - uses: actions/checkout@v3
      - run: cargo clippy
