name: Frontend Checks

on:
  pull_request:
    paths:
    - frontend/**
    - .github/workflows/check_frontend.yml
    paths-ignore:
    - frontend/src/i18n/locales/**

jobs:
  lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'yarn'
        cache-dependency-path: '**/yarn.lock'
    - run: yarn install --immutable
    - run: yarn lint --max-warnings 0

  typecheck:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'yarn'
        cache-dependency-path: '**/yarn.lock'
    - run: yarn install --immutable
    - run: yarn tsc
